### ISSUE TITLE
task: UI Mockup

### ISSUE THREAD

**Issue by AndrewH06** [paul-bokelman/sqnc#3]
## Description

Draw a mockup UI implementation with most features laid out.

Parent: #2

**Comment by AndrewH06** [comment]
<img width="948" alt="Screenshot 2023-12-02 at 6 30 28 PM" src="https://github.com/paul-bokelman/sqnc/assets/54915593/de96c349-8395-410e-89eb-9ca1218caeb8">
<img width="944" alt="Screenshot 2023-12-02 at 6 30 51 PM" src="https://github.com/paul-bokelman/sqnc/assets/54915593/c7d49fd9-0ecd-406a-89d8-cc9698a45c84">
<img width="837" alt="Screenshot 2023-12-02 at 6 31 35 PM" src="https://github.com/paul-bokelman/sqnc/assets/54915593/b7e1e277-200f-4b01-bcac-07e83a41b3fc">
<img width="837" alt="Screenshot 2023-12-02 at 6 31 45 PM" src="https://github.com/paul-bokelman/sqnc/assets/54915593/65936844-0a7b-4a53-9120-5cf6fdad9550">
<img width="829" alt="Screenshot 2023-12-02 at 6 45 20 PM" src="https://github.com/paul-bokelman/sqnc/assets/54915593/bf07a497-2b6e-4df3-8f9c-151aab773e2c">

**Comment by paul-bokelman** [comment]
Looks good but I think that the arrow keys and button should blend more into the background.
